name: publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: node-alpine
    env:
      SSH_USER: ${{ secrets.PUBLISHER_USER }}
      SSH_PRIVATE_KEY: ${{ secrets.PUBLISHER_PRIVATE_KEY }}
      SSH_HOST: ${{ secrets.PUBLISHER_HOST }}
      SSH_PORT: ${{ secrets.PUBLISHER_PORT }}
    steps:
      - name: Install dependencies
        run: |
          apk add git go hugo openssh-client rsync

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0 # all history for all branches and tags\

      - name: Build
        run: |
          hugo --minify

      - name: Deploy
        run: |
          mkdir -p -m 0600 ~/.ssh
          eval $(ssh-agent -s)
          echo "$SSH_PRIVATE_KEY" | ssh-add -
          ssh-keyscan -p $SSH_PORT $SSH_HOST > ~/.ssh/known_hosts
          rsync -atv --progress --delete -e "ssh -p $SSH_PORT" ./public/ $SSH_USER@$SSH_HOST:/app
